name: 'Publish'

on:
  push:
    branches:
      - master
jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: signal/
  publish:
    name: Publish
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        architecture: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.architecture }} \
            --target /data/signal