name: 'Test'

on:
  push:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: signal/

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: signal/root/app/requirements.txt
      - run: pip install -r signal/root/app/requirements.txt
      - run: pip install pytest
      - run: pytest signal/root
  build:
    name: Test action build
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        architecture: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Test ${{ matrix.architecture }} build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --${{ matrix.architecture }} \
            --target /data/signal
