name: 'Test'

on:
  push:

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: signal/

  build:
    name: Test action build
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        architecture: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Test ${{ matrix.architecture }} build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --${{ matrix.architecture }} \
            --target /data/signal